# Macro file for the initialization of example B4
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# material definition
/control/execute  material.mac
#
# physics list
/control/execute phys.mac
#
# Initialize kernel
/run/initialize
#
/control/execute Co60.mac
#